chat/urls.py
from django.urls import path
from . import views


app_name = 'chat'
urlpatterns = [
    path('' , views.HomeView , name='home') , 
    # path('room/<int:room_id>/', views.room_view, name='room'),
    path("<str:room_name>/<str:username>/", views.room_view, name="room"),
    path('list_of_rooms/' , views.room_list , name = 'room_list')
]

social_media/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'social_media'

urlpatterns = [
    path('' , views.index , name='all_videos') ,
    path('<int:id>/<slug:slug>', views.detail, name='video_detail'),
    path('new_video/<int:id>/' , views.new_video , name='new_video') , 
    path('all_your_comments/<int:id>/' , views.all_your_comments , name='all_your_comments') ,
    path('del_comment/<int:id>/' , views.del_comment , name='del_comment') , 
    path('del_video/<int:video_id>/<int:user_id>/' , views.del_video , name='del_video')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

social_net/urls.py
from django.contrib import admin 
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('social_media.urls')) , 
    path('users/' ,  include('users.urls')) , 
    path('chat/' ,  include('chat.urls')) , 
    ]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path , include
from . import views

app_name = 'users'

urlpatterns =[
    path('' , include('django.contrib.auth.urls') ) , 
    path('profile/<str:username>/', views.profile, name='profile'),
    path('register/' , views.register , name = 'register'), 
    path('edit_profile/<int:id>/' , views.edit_profile , name='edit_profile') , 
    # path('all_profiles/' ,views.all_profiles , name='all_profiles')
]

social_media/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
# Create your models here.


class Video(models.Model):
    title = models.CharField(max_length=200 , db_index=True)
    caption = models.CharField(max_length=1500)
    img = models.ImageField(upload_to='product/video/%Y' , blank=True ,  max_length=500 , null=True)
    video = models.FileField()
    slug = models.SlugField(max_length=200, db_index=True , unique= True )
    author = models.ForeignKey(User , on_delete=models.CASCADE , related_name='videos')


    def __str__(self) -> str:
        return self.title

    def get_absolute_url(self):
        return reverse('social_media:video_detail',
                        args=[self.id, self.slug])
    
    


class Comment(models.Model):
    video = models.ForeignKey(Video , on_delete= models.CASCADE , related_name='comment')
    text = models.TextField(max_length=1500 , null=True , blank=True)
    date_created = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User , on_delete=models.CASCADE)


    def __str__(self) -> str:
        return f'{self.text} by {self.author}'

social_media/forms.py
from django import forms
from .models import Comment , Video

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text' ]


class NewVideoForm(forms.ModelForm):
    class Meta:
        model = Video
        fields = ['title' , 'caption' , 'img' , 'video' , 'slug']

social_media/views.py
from django.shortcuts import render , get_object_or_404 , redirect
from .models import Video , Comment
from django.contrib.auth.decorators import login_required
from chat.models import Message , Room 
from users.models import Profile
from django.contrib.auth.models import User
from .forms import CommentForm , NewVideoForm
# Create your views here. 
@login_required(login_url = "users:login")
def index(request):
    video = Video.objects.all()
    return render(request , "social_media/index.html" , {'video' : video , })


def detail(request , id , slug):
    video = get_object_or_404( Video , id = id , slug = slug ) 
    comment = Comment.objects.filter(video = video)
    if request.method=='POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.video = video
            new_comment.author = request.user
            new_comment.save()
            return redirect('social_media:video_detail' ,  video.id , video.slug)
    else:
        form = CommentForm()
    return render(request , 'social_media/video_detail.html' , {'video' : video , 'comment' : comment , 'form' : form })

# def new_video(request , id):
#     user = get_object_or_404(User , id = id)
#     if request.method=='POST':
#         form = NewVideoForm()
#         if form.is_valid():
#             new_comment = form.save(commit=False)
#             new_comment.author = user
#             new_comment.save()
#             return redirect('users:profile' ,  user.id)
#     else:
#         form = NewVideoForm()
#     return render(request , 'social_media/new_video.html' , {'form' : form })



def new_video(request, id):
    user = get_object_or_404(User, id=id)
    if request.method == 'POST':
        form = NewVideoForm(request.POST , request.FILES)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.author = user
            new_comment.save()
            return redirect('users:profile', user.username)
    else:
        form = NewVideoForm()
    return render(request, 'social_media/new_video.html', {'form': form})



# def all_your_comments(request , id):
#     user = get_object_or_404(User , id = id)
#     comment = Comment.objects.filter( author = user )
#     video = Video.objects.filter(comment__in = comment)
#     return render(request , 'social_media/all_your_comments.html' , {'comment' : comment ,  'user' : user , 'video' : video})


def all_your_comments(request , id):
    user = get_object_or_404(User , id = id)
    comment = Comment.objects.filter( author = user ).select_related('video')
    return render(request , 'social_media/all_your_comments.html' , {'comment' : comment ,  'user' : user })

def del_comment(request, id):
    comment = get_object_or_404(Comment , id = id)
    video = get_object_or_404(Video , comment = comment)
    comment.delete()
    return redirect('social_media:all_your_comments' , request.user.id)

def del_video(request , video_id , user_id):
    user = get_object_or_404(User , id = user_id)
    video = get_object_or_404(Video , id = video_id ,  author = user)
    video.delete()
    return redirect('users:profile' , user.username )

templates/social_media/all_your_comments.html
{% extends "social_media/base.html" %}
{% load static %}

{% block content %}
    <div class="comments-container">
        <h2>Your Comments</h2>
        {% for i in comment  %}
            <div class="comment-item">
                <p class="comment-text">{{ i.text }}</p>
                {% if i.video%}
                <a href="{{ i.video.get_absolute_url }}">{{ i.video.title }}</a>
                <a href="{% url 'social_media:del_comment' i.id%}" class="btn-fourth" >Delete</a>
       
                {%endif%}
            </div>
        {% endfor %}
    </div>
{% endblock %}

templates/social_media/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'social_media/base.css' %}">
</head>
<body>
    <nav class="navbar">
        <div class="navbar-brand">
            <h1>Yess</h1>
        </div>
        <ul class="navbar-links">
            <li><a href="{% url 'chat:home' %}">Home</a></li>
            <li><a href="{% url 'social_media:all_videos' %}">Videos</a></li>
            {% if user.is_authenticated %}
                <li><a href="{% url 'social_media:new_video' user.id %}" >New Video</a></li>
                <li><a href="{% url 'chat:room_list' %}">My Chat</a></li>
                <li><a href="{% url 'users:profile' user.username %}">{{ user.username }}'s Profile</a>
</li>
                <li class="logout-form">
                    <form method="post" action="{% url 'users:logout' %}">
                        {% csrf_token %}
                        <button type="submit">Logout</button>
                    </form>
                </li>
            {% else %}
                <li><a href="{% url 'users:register' %}">Register</a></li>
                <li><a href="{% url 'users:login' %}">Log in</a></li>
            {% endif %}
        </ul>
    </nav>

    {% block content %}
    {% endblock %}
</body>
</html>

templates/social_media/index.html
{% extends "social_media/base.html" %}

{% block content %}
<div class="video-grid">
    {% for i in video %}
        <div class="video-item">
            {%if i.img%}
            <img src="{{ i.img.url }}" alt="{{ i.title }}">
            {%endif%}
            
            <a href="{{ i.get_absolute_url }}">
                <h3>{{ i.title }}</h3>
            </a>


    
        </div>
    {% endfor %}
</div>
{% endblock %}

templates/social_media/new_comment.html
{% comment %} {% extends "social_media/base.html" %} {% endcomment %}
{% load static %}
<head>
</head>
<h2>Add comment for product</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Add Comment</button>
</form>

templates/social_media/new_video.html
{% extends "social_media/base.html" %}
{% load static %}

{% block content %}
    <div class="form-container">
        <h2>Edit Profile</h2>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Save</button>
        </form>
    </div>
{% endblock %}

templates/social_media/video_detail.html
{% extends "social_media/base.html" %}
{% load static %}
{% block content %}
<div class="video-detail-container">
    <title>{{ video.title }}</title>
    <div class="video-wrapper">
        <video width="1280" height="720" controls>
            <source src="{{ video.video.url }}" type="video/mp4">
            Your browser does not support the video tag.
        </video>
    </div>
    <hr class="separator">
    <div class="caption_section">
        <h2>Author: {{ video.author }}</h2>
        <h2>Caption</h2>
        <h3>{{ video.caption }}</h3>
    </div>
    <div class="add_comment"">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Add Comment</button>
        </form>
    </form> 
    </div>
    <div class="comment_section">
        <h2>Comment Section</h2>
        {% for i in comment %}
        <div class="comment">
            <div class="comment_user">
                <img src="{% static 'profile_avs/no_image.png' %}" alt="Default Image" width="50">
                <span class="author_name">{{ i.author.username }}</span>
            </div>
            <p class="comment_text">{{ i.text }}</p>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}